version: '3.7'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Ecuador
      - SERVERPORT=51820 #optional
      - PEERS=2 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - C:\Users\Lu\Documents\Docker\docker-compose\Wireguard + PiHole\modules:/config
      - C:\Users\Lu\Documents\Docker\docker-compose\Wireguard + PiHole\src:/lib/modules
      - C:\Users\Lu\Documents\Docker\docker-compose\Wireguard + PiHole\wireguard:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 172.20.0.7
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 172.20.0.6

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    expose:
      - "53"
      - "67"
      - "80"
      - "443"
    environment:
      TZ: 'America/Ecuador'
      WEBPASSWORD: 'plastika'
    volumes:
      - 'C:\Users\Lu\Documents\Docker\docker-compose\Pi-hole\etc-dnsmasq.d:/etc/pihole/'
      - 'C:\Users\Lu\Documents\Docker\docker-compose\Pi-hole\etc-pihole:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 172.20.0.7

networks:
  containers:
    ipam:
      config:
        - subnet: 172.20.0.0/24